# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "Lemon juice")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Mint leaves")
Ingredient.create(name: "Lime")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Rum")
Ingredient.create(name: "Rhiskey")
Ingredient.create(name: "Soda")
Ingredient.create(name: "Coke")
Ingredient.create(name: "Sugar")
Ingredient.create(name: "Grenadine")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Orange juice")
Ingredient.create(name: "Tonic water")
Ingredient.create(name: "Sparkling wine")
Ingredient.create(name: "Aperol")
Ingredient.create(name: "Campari")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Orange")
Ingredient.create(name: "Lemon")
Ingredient.create(name: "Brown sugar")
Ingredient.create(name: "Basil")
Ingredient.create(name: "Olive")
Ingredient.create(name: "Honey")
Ingredient.create(name: "Rosemary")
Ingredient.create(name: "Cachaca")
Ingredient.create(name: "Bailey\'s")
Ingredient.create(name: "Ginger beer")
Ingredient.create(name: "Cream")
Ingredient.create(name: "Pineapple")
Ingredient.create(name: "Malibu")
